name: Automação de Backup S3

on:
  push:
    branches:
      - main  # Roda sempre que um push for feito na branch main

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Configurar LocalStack
        run: |
          docker run -d --name localstack -p 4566:4566 localstack/localstack
          sleep 20  # Espera 20 segundos para garantir que subiu

      - name: Verificar LocalStack
        run: |
          STATUS=$(curl -s http://localhost:4566/health | jq -r '.services.s3')
          if [[ "$STATUS" != "running" ]]; then
            echo "Erro: LocalStack não iniciou corretamente"
            exit 1
          fi

      - name: Criar diretório de backup se não existir
        run: mkdir -p ./backup

      - name: Criar bucket S3 no LocalStack
        run: aws --endpoint-url=http://localhost:4566 s3 mb s3://meu-bucket

      - name: Verificar buckets existentes
        run: aws --endpoint-url=http://localhost:4566 s3 ls

      - name: Garantir permissão do script
        run: chmod +x backup_monitor.py

      - name: Executar Script de Backup
        run: python backup_monitor.py
